"""initial database migration

Revision ID: dbc6ca1e4a1e
Revises: 
Create Date: 2020-05-15 16:15:07.371704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc6ca1e4a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('pair_pin', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('home_assistant',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('serial_key', sa.String(length=50), nullable=True),
    sa.Column('lat_long', sa.String(length=50), nullable=True),
    sa.Column('user_ID', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('serial_key', sa.String(length=100), nullable=True),
    sa.Column('lat_long', sa.String(length=50), nullable=True),
    sa.Column('user_ID', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('researcher_ID', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['researcher_ID'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('question_ID', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['question_ID'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('user_ID', sa.String(length=28), nullable=True),
    sa.Column('question_ID', sa.String(length=28), nullable=True),
    sa.Column('ask_question', sa.Boolean(), nullable=True),
    sa.Column('user_available', sa.String(length=20), nullable=True),
    sa.Column('device_to_use', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['question_ID'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_returned',
    sa.Column('id', sa.String(length=28), nullable=False),
    sa.Column('answer_time', sa.String(length=28), nullable=True),
    sa.Column('device_used', sa.String(length=20), nullable=True),
    sa.Column('user_ID', sa.String(length=28), nullable=True),
    sa.Column('answer_ID', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['answer_ID'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_returned')
    op.drop_table('user_details')
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('phone')
    op.drop_table('home_assistant')
    op.drop_table('user')
    op.drop_table('researcher')
    # ### end Alembic commands ###
